name: unit-test

on: [push, pull_request]

jobs:
  unit_test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 5
      matrix:
        os: [macos-latest, ubuntu-latest]
        py: ['3.8', '3.9', '3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.py }}
        
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install pytest and pytest-cov
      run: |
        pip install pytest pytest-cov
    - name: Install the package
      run:
        python setup.py install
        
    - name: Test with pytest
      run: |
        pytest --cov easy_fibo --cov-report term-missing --cov-report xml -vvv tests
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3.0.0
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        
      
          
    
    
